addSbtPlugin("nl.gn0s1s"        % "sbt-dotenv"      % "3.1.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"    % "2.5.5")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"    % "2.3.1")
addSbtPlugin("org.wartremover"  % "sbt-wartremover" % "3.4.0")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn"      % "0.1.3")
