name: Setup Nix
description: Install Nix and optionally setup Magic Nix Cache

inputs:
  enable-cache:
    description: Enable Magic Nix Cache
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      if: inputs.enable-cache == 'true'
      with:
        use-flakehub: false
