name: Deploy as Azure Function App

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: func-seat-stalker
  PACKAGE_DIRECTORY: "./azure-functions"
  JAVA_VERSION: "17"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build JAR
        run: sbt -v assembly

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
