name: Deploy as Azure Function App

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: func-seat-stalker
  PACKAGE_DIRECTORY: "./azure-functions"

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build JAR
        run: nix develop --command sbt -v assembly

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
